name: Martino Branding
favicon: null
layout_spectrum: 0.5172
typography_spectrum: 0.1861529171001166
title: Delicious Video Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23378487140871584
  lightness: 0.10294536151923239
  saturation: 0.9966370137408376
  rhythmicContrast: 0.2276909442152828
purpose: []
